# Generated by Django 5.1.4 on 2026-08-15 18:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_organization_letterhead_footer_offset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable public identifier used in URLs.', unique=True)),
                ('name', models.CharField(help_text='Product / Service Name as it should appear on invoices. Mandatory for both Goods and Services.', max_length=255)),
                ('product_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', help_text='Goods → HSN required; Service → SAC required.', max_length=10)),
                ('hsn_code', models.CharField(blank=True, help_text='Harmonised System of Nomenclature (HSN) code for Goods. 2–8 numeric digits. Required when product_type is Goods.', max_length=8)),
                ('sac_code', models.CharField(blank=True, help_text='Services Accounting Code (SAC) for Services. 4–6 numeric digits. Required when product_type is Service.', max_length=6)),
                ('taxability_type', models.CharField(choices=[('taxable', 'Taxable'), ('exempt', 'Exempt'), ('nil_rated', 'Nil-rated'), ('non_gst', 'Non-GST')], default='taxable', help_text='Taxability classification: Taxable / Exempt / Nil-rated / Non-GST. Each classification has distinct legal meaning under GST.', max_length=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Applicable GST rate percentage for this product (e.g. 18.00 for 18%). Sourced from centralized GST rate configuration in gst_config.py. Relevant when taxability_type is Taxable; stored but not enforced for Exempt / Nil-rated / Non-GST items.', max_digits=5)),
                ('cess_applicable', models.BooleanField(default=False, help_text='Whether GST Cess applies to this product.')),
                ('cess_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], help_text='Cess calculation method: Percentage or Fixed Amount per unit.', max_length=14)),
                ('cess_rate_or_amount', models.DecimalField(blank=True, decimal_places=4, help_text='When cess_type=Percentage: the cess percentage. When cess_type=Fixed Amount: the fixed amount per unit.', max_digits=10, null=True)),
                ('reverse_charge_applicable', models.BooleanField(default=False, help_text='Whether this product is subject to Reverse Charge Mechanism (RCM). This is a product-level default; the Invoice Engine makes the final RCM determination for each transaction.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Base unit price in INR. See price_basis to determine whether GST is included.', max_digits=12)),
                ('price_basis', models.CharField(choices=[('inclusive', 'Inclusive of GST'), ('exclusive', 'Exclusive of GST')], default='exclusive', help_text='Inclusive: unit_price already contains GST. Exclusive: GST is added on top of unit_price by the Invoice Engine.', max_length=10)),
                ('uqc', models.CharField(help_text='Unique Quantity Code (CBIC). Required for Goods (Rule 46 — GST invoice rules). Controlled list from gst_config.UQC_CHOICES.', max_length=3)),
                ('organization', models.ForeignKey(help_text='The organization that owns this product record.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'name'], name='products_pr_organiz_f39bcf_idx'), models.Index(fields=['organization', 'product_type'], name='products_pr_organiz_261179_idx')],
            },
        ),
    ]
