# Generated by Django 5.1.4 on 2026-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_archived_at_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Optional multi-line description of the product or service.'),
        ),
    ]
