# Generated by Django 5.1.4 on 2026-08-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='letterhead',
            field=models.ImageField(blank=True, help_text='Full A4 page background for invoices.', null=True, upload_to='organization_letterheads/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signature',
            field=models.ImageField(blank=True, help_text='Authorized signatory image.', null=True, upload_to='organization_signatures/'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
