# Generated by Django 5.1.4 on 2026-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_letterhead_organization_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='letterhead_footer_offset',
            field=models.IntegerField(default=25, help_text='Footer safe area offset in mm'),
        ),
        migrations.AddField(
            model_name='organization',
            name='letterhead_header_offset',
            field=models.IntegerField(default=30, help_text='Header safe area offset in mm'),
        ),
    ]
