# Generated by Django 5.1.4 on 2026-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_letterhead_footer_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code image displayed on invoices.', null=True, upload_to='organization_qr_codes/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', help_text='Default Terms & Conditions for invoices.'),
        ),
    ]
