# Generated by Django 5.1.4 on 2026-08-17 14:15

from django.db import migrations, models


def migrate_existing_signature_modes(apps, schema_editor):
    Organization = apps.get_model('organization', 'Organization')
    for org in Organization.objects.all():
        if org.signature:
            org.signature_mode = 'image'
            org.save(update_fields=['signature_mode'])


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, default='', help_text='Organization / Signatory text displayed when Authorized Signatory mode is selected.', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_computer_generated_disclaimer',
            field=models.BooleanField(default=False, help_text='Show disclaimer stating invoice is computer-generated and does not require signature.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signature_mode',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Signature Image'), ('authorized_signatory', 'Authorized Signatory')], default='none', help_text='Signature / Authorization mode for invoices.', max_length=20),
        ),
        migrations.RunPython(migrate_existing_signature_modes, reverse_code=migrations.RunPython.noop),
    ]
