# Generated by Django 5.1.4 on 2026-08-27 14:52

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_authorized_signatory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', help_text='Account plan: Free or Paid. Paid accounts do not receive the Advance Billing watermark on invoices.', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='letterhead',
            field=models.ImageField(blank=True, help_text='Full A4 page background for invoices.', null=True, upload_to='organization_letterheads/', validators=[apps.common.validators.validate_image_dimensions_and_format]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.common.validators.validate_image_dimensions_and_format]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code image displayed on invoices.', null=True, upload_to='organization_qr_codes/', validators=[apps.common.validators.validate_image_dimensions_and_format]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='signature',
            field=models.ImageField(blank=True, help_text='Authorized signatory image.', null=True, upload_to='organization_signatures/', validators=[apps.common.validators.validate_image_dimensions_and_format]),
        ),
    ]
