# Generated by Django 5.1.4 on 2026-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_upgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='demo_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique session ID owning this temporary demo organization.', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this is a temporary disposable demo organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Advance Billing Pro')], default='free', help_text='Account plan: Free or Paid. Paid accounts do not receive the Advance Billing watermark on invoices.', max_length=10),
        ),
    ]
