# Generated by Django 5.1.4 on 2026-08-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_organization_letterhead_footer_offset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=20)),
                ('gst_status', models.CharField(choices=[('registered', 'GST Registered'), ('unregistered', 'GST Unregistered')], default='registered', max_length=20)),
                ('name', models.CharField(help_text='Legal Registered Name (when GST Registered) or Customer Name (when Unregistered)', max_length=255)),
                ('gstin', models.CharField(blank=True, help_text='15-character GSTIN format for GST Registered customers', max_length=15)),
                ('billing_address_line_1', models.CharField(max_length=255)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_state_code', models.CharField(max_length=2)),
                ('billing_pin_code', models.CharField(max_length=10)),
                ('billing_country', models.CharField(default='India', max_length=100)),
                ('organization', models.ForeignKey(help_text='The organization owning this customer record.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'name'], name='customers_c_organiz_484379_idx'), models.Index(fields=['organization', 'gstin'], name='customers_c_organiz_337752_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gst_status', 'registered'), models.Q(('gstin', ''), _negated=True)), fields=('organization', 'gstin'), name='unique_registered_gstin_per_organization')],
            },
        ),
    ]
