# Generated by Django 5.1.4 on 2026-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_uuid_nonnull_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
