# Generated by Django 5.1.4 on 2026-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_archived_at_customer_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
