# Generated by Django 5.1.4 on 2026-08-16 04:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_uuid_nonnull_unique'),
        ('organization', '0003_organization_letterhead_footer_offset_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(max_length=100)),
                ('customer_name_snapshot', models.CharField(max_length=255)),
                ('customer_gstin_snapshot', models.CharField(blank=True, max_length=15)),
                ('customer_billing_address_snapshot', models.TextField()),
                ('customer_state_code_snapshot', models.CharField(max_length=2)),
                ('shipping_same_as_billing', models.BooleanField(default=True)),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_pincode', models.CharField(blank=True, max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cess_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('customer', models.ForeignKey(help_text='The customer billed for this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
                ('organization', models.ForeignKey(help_text='The organization owning this invoice.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organization.organization')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('product_type_snapshot', models.CharField(max_length=10)),
                ('hsn_sac_snapshot', models.CharField(blank=True, max_length=8)),
                ('taxability_type_snapshot', models.CharField(max_length=12)),
                ('gst_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cess_applicable_snapshot', models.BooleanField(default=False)),
                ('cess_type_snapshot', models.CharField(blank=True, max_length=14, null=True)),
                ('cess_rate_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reverse_charge_snapshot', models.BooleanField(default=False)),
                ('price_basis_snapshot', models.CharField(max_length=10)),
                ('uqc_snapshot', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('none', 'None')], default='none', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice', models.ForeignKey(help_text='The invoice this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('product', models.ForeignKey(help_text='The product this line item refers to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='billing_inv_organiz_527da0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'invoice_number'], name='billing_inv_organiz_77eb08_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'position'], name='billing_inv_invoice_26d8e3_idx'),
        ),
    ]
