# Generated by Django 5.1.4 on 2026-08-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0004_alter_uuid_nonnull_unique'),
        ('organization', '0003_organization_letterhead_footer_offset_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('organization', 'invoice_number'), name='unique_invoice_number_per_org'),
        ),
    ]
