# Generated by Django 5.1.4 on 2026-08-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_unique_invoice_number_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_last_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_last_trigger',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
