# Generated by Django 5.1.4 on 2026-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_email_last_error_invoice_email_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(blank=True, help_text='Optional line-item description. Populated from product but editable per invoice line.'),
        ),
    ]
