# Generated by Django 5.1.4 on 2026-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='destination',
            field=models.CharField(blank=True, default='', help_text='Optional custom destination / delivery location.', max_length=150),
        ),
    ]
