# Generated by Django on 2026-08-30

from django.db import migrations


def recycle_cancelled_invoices(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    InvoicePreference = apps.get_model('settings_app', 'InvoicePreference')
    Organization = apps.get_model('organization', 'Organization')

    # 1. Backfill and rename existing cancelled invoices with -CANCELLED suffix
    cancelled_invoices = Invoice.objects.filter(status='cancelled')
    for inv in cancelled_invoices:
        if not inv.invoice_number or '-CANCELLED' in inv.invoice_number:
            continue

        base_num = inv.invoice_number
        cancelled_num = f"{base_num}-CANCELLED"
        if Invoice.objects.filter(
            organization_id=inv.organization_id, invoice_number=cancelled_num
        ).exclude(pk=inv.pk).exists():
            cancelled_num = f"{base_num}-CANCELLED-{inv.pk}"

        inv.invoice_number = cancelled_num
        inv.save(update_fields=['invoice_number'])

    # 2. Reset starting_number for organizations where all issued invoices were cancelled
    for org in Organization.objects.all():
        owner = getattr(org, 'owner', None)
        if not owner:
            continue
        try:
            pref = InvoicePreference.objects.get(user=owner)
        except InvoicePreference.DoesNotExist:
            continue

        issued_invoices = Invoice.objects.filter(organization_id=org.id, status='issued')
        if not issued_invoices.exists():
            if pref.starting_number > 1:
                pref.starting_number = 1
                pref.save(update_fields=['starting_number'])


def reverse_recycle_cancelled_invoices(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_destination'),
        ('settings_app', '0004_documentpreference'),
    ]

    operations = [
        migrations.RunPython(recycle_cancelled_invoices, reverse_recycle_cancelled_invoices),
    ]
