# Generated by Django 5.1.4 on 2026-08-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(blank=True, default='INV', max_length=20)),
                ('starting_number', models.PositiveIntegerField(default=1)),
                ('include_financial_year', models.BooleanField(default=False)),
                ('default_payment_terms', models.CharField(choices=[('Receipt', 'Due on Receipt'), ('7', '7 Days'), ('15', '15 Days'), ('30', '30 Days'), ('Custom', 'Custom Days')], default='15', max_length=20)),
                ('custom_payment_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_notes', models.TextField(blank=True, default='Thank you for your business.')),
                ('default_terms', models.TextField(blank=True)),
                ('default_currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='INR', max_length=10)),
                ('decimal_places', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2)),
                ('rounding_method', models.CharField(choices=[('Normal', 'Normal'), ('Up', 'Round Up'), ('Down', 'Round Down')], default='Normal', max_length=10)),
                ('draft_by_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
