# Generated by Django 5.1.4 on 2026-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_invoicepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepreference',
            name='decimal_places',
            field=models.IntegerField(choices=[(0, '0'), (2, '2'), (3, '3')], default=2),
        ),
        migrations.AlterField(
            model_name='invoicepreference',
            name='default_terms',
            field=models.TextField(blank=True, default='Goods once sold will not be taken back.\nSubject to Ahmedabad jurisdiction.'),
        ),
        migrations.AlterField(
            model_name='invoicepreference',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', max_length=15),
        ),
    ]
