# Generated by Django 5.1.4 on 2026-08-07 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_invoicepreference_decimal_places_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('professional', 'Professional Template'), ('classic', 'Classic Template'), ('minimal', 'Minimal Template'), ('modern', 'Modern Template')], default='professional', max_length=20)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], default='Portrait', max_length=15)),
                ('margins', models.CharField(choices=[('Narrow', 'Narrow'), ('Normal', 'Normal'), ('Wide', 'Wide')], default='Normal', max_length=10)),
                ('show_company_logo', models.BooleanField(default=True)),
                ('show_company_header', models.BooleanField(default=True)),
                ('show_company_footer', models.BooleanField(default=True)),
                ('print_on_letterhead', models.BooleanField(default=False)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('show_bank_details', models.BooleanField(default=True)),
                ('show_gst_summary', models.BooleanField(default=True)),
                ('show_hsn_sac', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=True)),
                ('show_terms', models.BooleanField(default=True)),
                ('show_payment_info', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10)),
                ('table_density', models.CharField(choices=[('Compact', 'Compact'), ('Comfortable', 'Comfortable')], default='Comfortable', max_length=15)),
                ('show_page_numbers', models.BooleanField(default=True)),
                ('show_print_date', models.BooleanField(default=True)),
                ('custom_footer_message', models.TextField(blank=True, default='Thank you for your business.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
