# Generated by Django 5.1.4 on 2026-08-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_documentpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreference',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
