# Generated by Django 5.1.4 on 2026-08-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_documentpreference_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpreference',
            name='template_name',
            field=models.CharField(choices=[('professional', 'Professional Template'), ('classic', 'Classic Template'), ('minimal', 'Minimal Template'), ('modern', 'Modern Template'), ('gst_classic', 'GST Classic')], default='gst_classic', max_length=20),
        ),
    ]
