# Generated by Django 5.1.4 on 2026-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_alter_documentpreference_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpreference',
            name='template_name',
            field=models.CharField(choices=[('gst_classic', 'GST Classic'), ('flipkart_invoice', 'Flipkart Invoice'), ('retail_gst_compact', 'Retail GST Compact')], default='gst_classic', max_length=20),
        ),
    ]
