# Generated by Django 5.1.4 on 2026-08-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_alter_documentpreference_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpreference',
            name='template_name',
            field=models.CharField(choices=[('gst_classic', 'GST Classic'), ('flipkart_invoice', 'Flipkart Invoice'), ('retail_gst_compact', 'Retail GST Compact'), ('evergreen', 'Evergreen Template'), ('compact_template', 'Compact Template'), ('genz', 'GenZ Template'), ('landscape_template', 'Landscape GST Invoice'), ('modern_template', 'Modern Invoice'), ('mrp_discount_template', 'MRP + Discount Invoice'), ('professional_template', 'Professional Invoice'), ('service_template', 'Service Invoice'), ('vintage', 'Vintage Invoice')], default='gst_classic', max_length=30),
        ),
    ]
