# Generated by Django 5.1.4 on 2026-08-14 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0010_alter_documentpreference_template_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTemplate',
            fields=[
                ('slug', models.SlugField(help_text="Must match the filename stem in templates/pdf/ (e.g. 'compact_template').", max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable display name.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_file_path', models.CharField(help_text="Relative template path understood by Django's template loader (e.g. 'pdf/compact_template.html').", max_length=255)),
                ('preview_image', models.ImageField(blank=True, help_text='Thumbnail shown in the Invoice Design gallery.', null=True, upload_to='bill_template_previews/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from the gallery but still renderable.')),
                ('default_config', models.JSONField(default=dict, help_text='JSON object describing this template\'s capabilities and default preference values. Keys that are False/absent mean the template does not support that element. Example: {"has_qr": true, "has_signature": true, "show_gst_summary": true}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBillPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_overrides', models.JSONField(default=dict, help_text="User's overrides for this template's default_config.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='settings_app.billtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template__name'],
                'unique_together': {('user', 'template')},
            },
        ),
    ]
