# Generated by Django 5.1.4 on 2026-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_billtemplate_userbillpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpreference',
            name='template_name',
            field=models.CharField(choices=[('gst_classic', 'GST Classic'), ('flipkart_invoice', 'Flipkart Invoice'), ('retail_gst_compact', 'Retail GST Compact'), ('evergreen', 'Evergreen Template'), ('compact_template', 'Compact Template'), ('genz', 'GenZ Template'), ('landscape_template', 'Landscape Template'), ('modern_template', 'Modern Template'), ('mrp_discount_template', 'MRP Discount Template'), ('professional_template', 'Professional Template'), ('service_template', 'Service Template'), ('vintage', 'Vintage Template'), ('ledger_classic', 'Ledger Classic'), ('minimal_mono', 'Minimal Mono'), ('bold_header', 'Bold Header'), ('elegant_serif', 'Elegant Serif'), ('tech_grid', 'Tech Grid')], default='gst_classic', max_length=30),
        ),
    ]
