# Generated by Django 5.1.4 on 2026-08-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_authorized_signatory_name_and_more'),
        ('settings_app', '0014_alter_documentpreference_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Weekly Scheduled'), ('manual', 'Manual Export')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('never', 'Never generated'), ('scheduled', 'Scheduled'), ('generating', 'Generating'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_backup_enabled', models.BooleanField(default=False)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('next_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never generated'), ('scheduled', 'Scheduled'), ('generating', 'Generating'), ('sent', 'Sent'), ('failed', 'Failed')], default='never', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_record_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_setting', to='organization.organization')),
            ],
        ),
    ]
