# Generated by Django 5.1.4 on 2026-08-26 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_authorized_signatory_name_and_more'),
        ('settings_app', '0015_organizationbackuplog_organizationbackupsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataManagementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('export', 'Data Export'), ('import', 'Data Import'), ('weekly_backup_toggle', 'Weekly Backup Toggle'), ('backup_sent', 'Backup Sent'), ('backup_failed', 'Backup Failed'), ('archive', 'Archive Records'), ('restore_archived', 'Restore Archived Records'), ('cleanup', 'Data Cleanup'), ('restore_backup', 'Restore from Backup'), ('permanent_delete', 'Permanent Data Deletion')], max_length=30)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_management_audit_logs', to='organization.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_management_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
