# Generated by Django 5.1.4 on 2026-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0016_datamanagementauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_city',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_country',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_gstin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_pincode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentpreference',
            name='show_customer_state',
            field=models.BooleanField(default=True),
        ),
    ]
