# Generated by Django 5.1.4 on 2026-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0017_documentpreference_show_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreference',
            name='show_place_of_supply',
            field=models.BooleanField(default=True),
        ),
    ]
